apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: example-{{ .Release.Name }}
spec:
  rules:
  - host: httpd.todosrus.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: httpd-{{ .Release.Name }}
          servicePort: 80
  - host: nginx.todosrus.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-{{ .Release.Name }}
          servicePort: 80

