configMapGenerator:
- name: example
  files:
  - application.properties
nameSuffix: "-project"
commonLabels:
  app.kubernetes.io/name: project
  app.kubernetes.io/instance: project
  app.kubernetes.io/version: 0.1.0

