apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}  
  name: flask-{{ .Release.Name }}
  namespace: production-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}  
        app: flask
        release: {{ .Release.Name }}
        networking/logic: "true"
    spec:
      containers:
      - name: flask
        env:
        - name: REDIS_URL
          value: {{ printf "redis://data-%s" .Release.Name }}
        image: 143287522423.dkr.ecr.us-east-1.amazonaws.com/todos:0.1.0
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /probe
            port: http

